// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using maxcash.backend.repository.contexto;

namespace maxcash.backend.repository.Migrations
{
    [DbContext(typeof(MaxCashDbContext))]
    partial class MaxCashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DB_MAXCASH")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("maxcash.backend.model.entidades.Conta", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CONTA")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdicionaDashBoard");

                    b.Property<string>("Cor");

                    b.Property<string>("DescricaoTipoConta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME_CONTA")
                        .HasMaxLength(128);

                    b.Property<decimal>("Saldo");

                    b.Property<int>("TipoConta");

                    b.HasKey("ContaId");

                    b.ToTable("TB_CONTAS");
                });

            modelBuilder.Entity("maxcash.backend.model.entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_USUARIO")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("NASCIMENTO_USUARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL_USUARIO")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME_USUARIO")
                        .HasMaxLength(128);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA_USUARIO")
                        .HasMaxLength(480);

                    b.Property<string>("Situacao")
                        .HasColumnName("SITUACAO_USUARIO");

                    b.HasKey("UsuarioId");

                    b.ToTable("TB_USUARIOS");
                });
#pragma warning restore 612, 618
        }
    }
}
